package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

import javafx.scene.control.DatePicker;

public class editInstructorPanelController {
	@FXML
	private RadioButton mButton;
	@FXML
	private ToggleGroup radioGroup;
	@FXML
	private RadioButton fButton;
	@FXML
	private TextField firstNameField;
	@FXML
	private TextField lastNameField;
	@FXML
	private TextField addressField;
	@FXML
	private TextField zipField;
	@FXML
	private TextField phoneField;
	@FXML
	private TextField emailField;
	@FXML
	private DatePicker bdate;
	@FXML
	private TextField idField;
	@FXML
	private Button submitButton;
	@FXML
	private Button resetButton;
	@FXML
	private ComboBox<String> deptCombo;

	private InstructorAccessor idb;
	private DeptAccessor db;
	private Instructor instructor;
	ObservableList<Department> deptList;
	
	public editInstructorPanelController(Instructor in)
	{
		instructor = in;
		idb = new InstructorAccessor();
	
	}
	@FXML 
	void initialize()
	{
		db = new DeptAccessor();
		
		ObservableList<Department> deptList;
		try {
			deptList = db.getDepartmentList();
			ArrayList<String> nameList = new ArrayList<>();
			int len = deptList.size();
			for (int i = 0; i < len; i++)
			{
				nameList.add(deptList.get(i).getName());
			}
			deptCombo.getItems().addAll(nameList);
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		firstNameField.setText(instructor.getFirstName());
		lastNameField.setText(instructor.getLastName());
		String gender = instructor.getGender();
		if (gender.equals("Male"))
		{
			mButton.setSelected(true);
			mButton.requestFocus();
		}
		else if (gender.equals("Female"))
		{
			fButton.setSelected(true);
			fButton.requestFocus();
		}
		addressField.setText(instructor.getAddress());
		zipField.setText(instructor.getZipCode());
		deptCombo.setValue(instructor.getInstructorDepartment());
		phoneField.setText(instructor.getPhoneNumber());
		emailField.setText(instructor.getEmail());
		String bday = instructor.getBirthDate();
		LocalDate date = LocalDate.parse(bday);
		bdate.setValue(date);
		idField.setText(Integer.toString(instructor.getInstructorID()));
		
		
		
	}
	
	@FXML
	public void handleSubmit(ActionEvent event) {
		Instructor inst = null;
		String firstName, lastName, address, zip, phone,
		email, bd, gender;
		
		firstName = firstNameField.getText();
		lastName = lastNameField.getText();
		address = addressField.getText();
		zip = zipField.getText();
		phone = phoneField.getText();
		bd = bdate.getValue().toString();
		email = emailField.getText();
		if (mButton.isSelected())
		{
			gender = "Male";
		}
		else
		{
		gender = "Female";
		}
		int id = Integer.parseInt(idField.getText());
		String dep = deptCombo.getValue();
		inst = new Instructor(firstName, lastName, gender, address, phone, zip, bd, email, id, dep);

		idb.updateInstructor(inst);
		
		submitButton.getScene().getWindow().hide();
	}
	// Event Listener on Button[#resetButton].onAction
	@FXML
	public void handleReset(ActionEvent event) {
		// TODO Autogenerated
	}
}
